### ISSUE TITLE
Increase timeout

### ISSUE THREAD

**Issue by natanfelles** [mjanser/php-systemctl#3]
What about to increase or add a way to increase the timeout?

https://github.com/mjanser/php-systemctl/blob/342a8c99f43a8b897b82ac749995644135801f17/Service.php#L178

3 seconds is not so easy to type a root password. After the timeout the bash do not back to normal, does not accepts commands and `Ctrl + C` also do not works.

I'm using Symfony Console:

```php
$service = $input->getArgument('service');

$service = new SystemCtl\Service($service);

if ($service->isRunning())
{
	$output->writeln("The service {$service} already is running.");
}
else
{
	$service->start();
}
```

Running my command `lemp start nginx` the terminal prompts the password but have not time to type... Then the exception is showed and the terminal bug.

```
[Symfony\Component\Process\Exception\ProcessTimedOutException]                                    
  The process "'sudo' 'systemctl' '--lines=0' 'status' 'nginx'" exceeded the timeout of 3 seconds. 
```

**Comment by mjanser** [comment]
I added a timeout setting now. You can use something like this:
```
SystemCtl\Service::setTimeout(60);
```

But I would recommend you to set up `sudo` to not require a password for those commands.

**Comment by natanfelles** [comment]
Oh, yes. Thank you very much @mjanser !
